steps:
  - name: build
    # image: pandoc/latex:2-alpine
    image: nopreserveroot/rubber:2023.04.20
    commands:
      # since its an old ubuntu image
      - curl -s -o /etc/apt/sources.list https://gist.githubusercontent.com/ishad0w/788555191c7037e249a439542c53e170/raw/3822ba49241e6fd851ca1c1cbcc4d7e87382f484/sources.list
      - apt-get -y update && apt-get -y install make fonts-noto fonts-noto-ui-core fonts-noto-ui-extra
      - make

  # since release plugin only accepts tag events
  - name: publish
    image: curlimages/curl-base:8.6.0
    secrets:
      - source: release_token
        target: TOKEN
    # TODO: url as a env variable
    commands:
      - apk update && apk add jq
      - export ATTACH_ID=$$(curl -s -X "GET" "https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets?access_token=$TOKEN" | jq ".[-1].id")
      - echo $${ATTACH_ID}
      - curl -X "GET" "https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets/?access_token=$TOKEN" | jq ".[-1].id"
      - curl -X 'DELETE' "https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets/$${ATTACH_ID}?access_token=$TOKEN" 
      - curl -X 'POST' "https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets?access_token=$TOKEN" -F "attachment=@dcssbook.pdf;type=application/pdf"


  # - name: publish
  #   image: woodpeckerci/plugin-gitea-release
  #   settings:
  #     base_url: https://codeberg.org
  #     title: latest
  #     target: main
  #     files:
  #       - "dcss-book.pdf"
  #     api_key:
  #       from_secret: RELEASE_TOKEN
