name: Codeberg mirror on gh

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: clone codeberg repo
        run: git clone --bare https://codeberg.org/mhtajari/dcss-book

      - name: push to mirror
        working-directory: ./dcss-book.git

        run: git push --mirror https://mohammad5305:${{ secrets.GITHUB_TOKEN }}@github.com/mohammad5305/dcss_book.git

  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4

       - name: Install deps
         uses: awalsh128/cache-apt-pkgs-action@latest
         with:
           packages: noto-fonts fonts-noto-ui-core fonts-noto-ui-extra rubber jq
           version: 1.0

        # its not cached because of installation problems
       # https://bugzilla.redhat.com/show_bug.cgi?id=1651282

       - name: Install latex
         run : | 
           sudo apt update && sudo apt install texlive-xetex texlive-base texlive-fonts-extra texlive-lang-arabic texlive-extra-utils 

       - name: build
         run: make

       - name: push to codeberg release
         run: |
            ATTACH_ID=$(curl -X 'GET' \
            'https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets?access_token=${{ secrets.API_TOKEN }}' \
            -H 'accept: application/json' | jq -r '.[-1].id')

            echo $ATTACH_ID

            curl -X 'DELETE' \
            "https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets/$ATTACH_ID?access_token=${{ secrets.API_TOKEN }}" -H 'accept: application/json'

            curl -X 'POST' 'https://codeberg.org/api/v1/repos/mhtajari/dcss-book/releases/1925484/assets?access_token=${{ secrets.API_TOKEN }}' \
            -H 'accept: application/json' \
            -H 'Content-Type: multipart/form-data' \
            -F 'attachment=@dcssbook.pdf;type=application/pdf'
